Serial.IOException: do not filter exception logging based on .getMessage()
as this contains errno converted to text, so depends on the current locale.